### ISSUE TITLE
יצירת אוטומציה שבונה גיליון

### ISSUE THREAD

**Issue by ShayCohen01** [ofriperetz/VWR#15]
נרצה פונקציה שבונה גיליון באופן אוטומטי בהינתן תכונות בסיסיות:

- כותרת הגיליון (לדוגמא : "פניות - חריגים") 

- מקרא

- עמודות רצויות בגיליון החדש (על פי סדר מבוקש)

**Comment by ShayCohen01** [comment]
![gilayon](https://user-images.githubusercontent.com/62832893/78067263-1656c100-739f-11ea-9e58-257edf6136a3.jpg)

**Comment by ofriperetz** [comment]
אני מחבר לכאן קישור לפרויקט Git שמצאתי שממש בדיוק במשהו דומה,
זו משימה קצת יותר מורכבת ובשלב הראשון המטרה שלנו להצליח לבנות גיליון בלי עיצוב בכלל.

[פרויקט שמימש בצורה גנרית יצירת ראיון](https://github.com/18F/tock-gas-ts)

**Comment by ofriperetz** [comment]
לוקח על עצמי את המשימה,
בונה לנו תשתית ולאחר מכן אחד המפתחים ימשיך אותי.
