### ISSUE TITLE
suggestion - for a more readable code

### ISSUE THREAD

**Issue by aviad59** [ofriperetz/VWR#6]
maybe instead of writing all the functions in the same file we could move all the boolean functions to a separate file, that way the main file ("public.ts")  will be more readable.

@ofriperetz what do you think? though its a small change i believe it can lead to a better code arrangement.

**Comment by ofriperetz** [comment]
Agree.
What do you think about moving the big functions which handle the operation from moving a request from one sheet to another to seperate files.
Do it and add a pull request, try to choose good naming tho.

**Comment by aviad59** [comment]
So if i understood you correctly you suggest creating a separate file for each function right? Besides the file containing the boolean functions.

**Comment by ofriperetz** [comment]
Yes, do the changes you see that necessary, create a pull request and I will code review your work, give you comments for fixes and we will merge the code!
btw add more comments if you see it useful.

**Comment by ofriperetz** [comment]
I see this issue as closed.
