### ISSUE TITLE
שמירת משימות סגורות ומבוטלות בקובץ נפרד

### ISSUE THREAD

**Issue by ofriperetz** [ofriperetz/VWR#7]
כלומר-פיצול המערכת לפניות הפתוחות בקובץ אחד
פניות סגורות/מבוטלות בקובץ שני.

ידרוש גישה לקובץ נוסף, יש לעשות שימוש ב-
[Open another Spreadsheet by Id.](https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet-app#openById(String))

**Comment by nitay737** [comment]
spreadsheats רק כדי להיות בטוח אתה רוצה לפצל את המערכת שיהיה שני  
באחד את הפעילים ובשני את הסגורים והמבוטלים כלומר להחליף את הארכיון?
כי ראיתי שיש בקובץ לשוניות שקוראים להם ארכיון אז בעצם הפעולה הזו תחליף אותם?
